"""Base adapter for audio LLM models.

Each audio LLM family has different prompt formats and output structures.
Adapters normalize these differences behind a common interface.
"""

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any

from dalston.common.pipeline_types import Transcript


class AudioLLMAdapter(ABC):
    """Base class for model-specific prompt building and output parsing.

    Subclasses implement:
    - build_messages(): Build chat messages with audio for vLLM
    - parse_output(): Parse raw model text to Transcript
    """

    @abstractmethod
    def build_messages(
        self,
        audio_path: Path,
        language: str | None = None,
    ) -> list[dict[str, Any]]:
        """Build model-specific chat messages with audio input.

        Args:
            audio_path: Path to the audio file (16kHz mono WAV)
            language: ISO 639-1 language code, or None for auto-detect

        Returns:
            List of message dicts in OpenAI chat format for vLLM
        """
        raise NotImplementedError

    @abstractmethod
    def parse_output(
        self,
        raw_text: str,
        language: str | None = None,
        duration: float | None = None,
    ) -> Transcript:
        """Parse model output to Transcript.

        Args:
            raw_text: Raw text generated by the model
            language: Language code used for transcription
            duration: Optional audio duration in seconds

        Returns:
            Transcript with text and segments
        """
        raise NotImplementedError

    def get_sampling_kwargs(self) -> dict[str, Any]:
        """Return model-specific sampling parameters.

        Override to customize temperature, max_tokens, etc.

        Returns:
            Dict of kwargs for vLLM SamplingParams
        """
        return {
            "temperature": 0.0,
            "max_tokens": 4096,
        }
