schema_version: "1.1"
id: faster-whisper-base
stage: transcribe
name: Faster Whisper Base
version: 1.0.0
description: |
  OpenAI Whisper base model via faster-whisper (CTranslate2).
  Good balance of speed and accuracy for general transcription.
  Supports 99 languages with automatic language detection.

container:
  gpu: optional
  memory: 4G
  model_cache: /models

capabilities:
  languages:
    - all  # 99 languages supported
  max_audio_duration: 7200  # 2 hours
  streaming: false
  word_timestamps: false  # Has timestamps but they're inaccurate; use alignment stage
  max_concurrency: 4

input:
  audio_formats:
    - wav
  sample_rate: 16000
  channels: 1

hf_compat:
  pipeline_tag: automatic-speech-recognition
  library_name: ctranslate2
  license: mit
  source_model: "Systran/faster-whisper-base"

hardware:
  min_vram_gb: 2
  recommended_gpu:
    - t4
  supports_cpu: true
  min_ram_gb: 4

performance:
  rtf_gpu: 0.03
  rtf_cpu: 0.4
  warm_start_latency_ms: 30
