#!/usr/bin/env python3
"""Generate the gateway/orchestrator settings reference from Pydantic fields."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from dalston.config import Settings

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "reference" / "configuration.md"


def _default(value: Any) -> str:
    if value is None:
        return "unset"
    if isinstance(value, str):
        return f"`{value}`"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    return f"`{value}`"


def render() -> str:
    rows: list[str] = []
    for field in Settings.model_fields.values():
        name = field.alias
        description = (field.description or "").replace("\n", " ").replace("|", "\\|")
        rows.append(f"| `{name}` | {_default(field.default)} | {description} |")

    table = "\n".join(rows)
    return f"""# Configuration reference

<!-- Generated by scripts/generate_config_reference.py; do not edit by hand. -->

This table is generated from `dalston.config.Settings`. It covers
gateway/orchestrator settings owned by that model. Engine-specific variables
remain documented with their engine or subsystem.

| Environment variable | Default | Description |
| --- | --- | --- |
{table}

## Mode-specific behavior

`DALSTON_MODE=lite` changes the retention default to `0` only when
`DALSTON_RETENTION_DEFAULT_DAYS` was not explicitly supplied. It also selects
the SQLite/local-artifact dependencies described by the Lite capability API.

`DALSTON_SECURITY_MODE=none` is intended only for trusted local development.
Change `DALSTON_WEBHOOK_SECRET` and example database/object-storage credentials
before any non-local deployment.

## Other subsystem variables

Some runtime settings are intentionally not part of the central Pydantic
model:

- Model source/cache: `DALSTON_MODEL_SOURCE`, `DALSTON_MODEL_CACHE_DIR`,
  `DALSTON_MODEL_CACHE_MAX_GB`, `DALSTON_MODEL_CACHE_TTL_HOURS`, and
  `DALSTON_MODEL_CACHE_SCAN_INTERVAL`.
- Realtime lag: `DALSTON_REALTIME_LAG_WARNING_SECONDS`,
  `DALSTON_REALTIME_LAG_HARD_SECONDS`, and
  `DALSTON_REALTIME_LAG_HARD_GRACE_SECONDS`.
- Optional batch speech-region diagnostics:
  `DALSTON_PREPARE_SPEECH_REGIONS`.
- Engine/device credentials and tuning, including `HF_TOKEN`,
  `DALSTON_DEVICE`, and engine-specific batch/concurrency variables.

Use `.env.example`, the relevant engine's `engine.yaml`/README, and code search
for subsystem settings. Never copy credentials from a development `.env` into
cloud deployment shells.

## Regeneration

```bash
.venv/bin/python scripts/generate_config_reference.py
.venv/bin/python scripts/generate_config_reference.py --check
```
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in reference is not current",
    )
    args = parser.parse_args()
    content = render()

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; regenerate it")
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is current")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
